using ContextExplained.Core.Entities;

namespace ContextExplained.Core.ValueObjects;

public static class LessonPathsArchive
{
    public static readonly Dictionary<string, int> Chronological = new Dictionary<string, int>
    {
        {"Genesis", 1},
        {"Job", 2},
        {"Exodus", 3},
        {"Leviticus", 4},
        {"Numbers", 5},
        {"Deuteronomy", 6},
        {"Joshua", 7},
        {"Judges", 8},
        {"Ruth", 9},
        {"1 Samuel", 10},
        {"2 Samuel", 11},
        {"1 Chronicles", 12},
        {"2 Chronicles", 13},
        {"Psalms", 14},
        {"Proverbs", 15},
        {"Ecclesiastes", 16},
        {"Song of Solomon", 17},
        {"1 Kings", 18},
        {"2 Kings", 19},
        {"Obadiah", 20},
        {"Jonah", 21},
        {"Amos", 22},
        {"Micah", 23},
        {"Isaiah", 24},
        {"Hosea", 25},
        {"Nahum", 26},
        {"Zephaniah", 27},
        {"Jeremiah", 28},
        {"Habakkuk", 29},
        {"Lamentations", 30},
        {"Ezekiel", 31},
        {"Joel", 32},
        {"Daniel", 33},
        {"Ezra", 34},
        {"Haggai", 35},
        {"Zechariah", 36},
        {"Esther", 37},
        {"Nehemiah", 38},
        {"Malachi", 39},
        {"Luke", 40},
        {"John", 41},
        {"Matthew", 42},
        {"Mark", 43},
        {"Acts", 44},
        {"James", 45},
        {"Galatians", 46},
        {"1 Thessalonians", 47},
        {"2 Thessalonians", 48},
        {"1 Corinthians", 49},
        {"2 Corinthians", 50},
        {"Romans", 51},
        {"Colossians", 52},
        {"Philemon", 53},
        {"Ephesians", 54},
        {"Philippians", 55},
        {"1 Timothy", 56},
        {"Titus", 57},
        {"1 Peter", 58},
        {"Hebrews", 59},
        {"2 Timothy", 60},
        {"2 Peter", 61},
        {"Jude", 62},
        {"1 John", 63},
        {"2 John", 64},
        {"3 John", 65},
        {"Revelation", 66 },
    };
}