using ContextExplained.Core.Entities;

namespace ContextExplained.Core.ValueObjects;

public static class LessonPathsArchive
{
    public static readonly Dictionary<BibleBook, int> Chronological = new()
    {
        { BibleBook.Genesis, 1 },
        { BibleBook.Job, 2 },
        { BibleBook.Exodus, 3 },
        { BibleBook.Leviticus, 4 },
        { BibleBook.Numbers, 5 },
        { BibleBook.Deuteronomy, 6 },
        { BibleBook.Joshua, 7 },
        { BibleBook.Judges, 8 },
        { BibleBook.Ruth, 9 },
        { BibleBook.Samuel1, 10 },
        { BibleBook.Samuel2, 11 },
        { BibleBook.Chronicles1, 12 },
        { BibleBook.Chronicles2, 13 },
        { BibleBook.Psalms, 14 },
        { BibleBook.Proverbs, 15 },
        { BibleBook.Ecclesiastes, 16 },
        { BibleBook.SongOfSolomon, 17 },
        { BibleBook.Kings1, 18 },
        { BibleBook.Kings2, 19 },
        { BibleBook.Obadiah, 20 },
        { BibleBook.Jonah, 21 },
        { BibleBook.Amos, 22 },
        { BibleBook.Micah, 23 },
        { BibleBook.Isaiah, 24 },
        { BibleBook.Hosea, 25 },
        { BibleBook.Nahum, 26 },
        { BibleBook.Zephaniah, 27 },
        { BibleBook.Jeremiah, 28 },
        { BibleBook.Habakkuk, 29 },
        { BibleBook.Lamentations, 30 },
        { BibleBook.Ezekiel, 31 },
        { BibleBook.Joel, 32 },
        { BibleBook.Daniel, 33 },
        { BibleBook.Ezra, 34 },
        { BibleBook.Haggai, 35 },
        { BibleBook.Zechariah, 36 },
        { BibleBook.Esther, 37 },
        { BibleBook.Nehemiah, 38 },
        { BibleBook.Malachi, 39 },
        { BibleBook.Luke, 40 },
        { BibleBook.John, 41 },
        { BibleBook.Matthew, 42 },
        { BibleBook.Mark, 43 },
        { BibleBook.Acts, 44 },
        { BibleBook.James, 45 },
        { BibleBook.Galatians, 46 },
        { BibleBook.Thessalonians1, 47 },
        { BibleBook.Thessalonians2, 48 },
        { BibleBook.Corinthians1, 49 },
        { BibleBook.Corinthians2, 50 },
        { BibleBook.Romans, 51 },
        { BibleBook.Colossians, 52 },
        { BibleBook.Philemon, 53 },
        { BibleBook.Ephesians, 54 },
        { BibleBook.Philippians, 55 },
        { BibleBook.Timothy1, 56 },
        { BibleBook.Titus, 57 },
        { BibleBook.Peter1, 58 },
        { BibleBook.Hebrews, 59 },
        { BibleBook.Timothy2, 60 },
        { BibleBook.Peter2, 61 },
        { BibleBook.Jude, 62 },
        { BibleBook.John1, 63 },
        { BibleBook.John2, 64 },
        { BibleBook.John3, 65 },
        { BibleBook.Revelation, 66 }
    };
}